"""Derive the root explorer from its single source, rebasing local asset links."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from urllib.parse import urljoin, urlsplit, urlunsplit

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROUTE = "resources/sppt-scm-research-companion/draft-v0.1.0/explorer/"
SOURCE = ROOT / SOURCE_ROUTE / "index.html"
OUTPUT = ROOT / "docs/index.html"
TAGS = re.compile(r"<(?:a|img|source|video|link)\b[^>]*>", re.IGNORECASE)
URL_ATTRIBUTE = re.compile(r'\b(href|src|poster)="([^"]*)"')


def root_reference(destination: str) -> str:
    """Leave fragments and external URLs intact; preserve local query/fragment."""
    parsed = urlsplit(destination)
    if not destination or destination.startswith(("#", "/")) or parsed.scheme:
        return destination
    resolved = urlsplit(urljoin("https://gateway.invalid/" + SOURCE_ROUTE, destination))
    return urlunsplit(("", "", resolved.path.lstrip("/") or "./", resolved.query, resolved.fragment))


def render(source: str) -> str:
    if re.search(r"<base\b", source, re.IGNORECASE):
        raise RuntimeError("Explorer links must not depend on a base element")

    def tag(match: re.Match[str]) -> str:
        return URL_ATTRIBUTE.sub(
            lambda attr: f'{attr[1]}="{root_reference(attr[2])}"', match[0],
        )

    return TAGS.sub(tag, source).replace(
        "<!doctype html>",
        "<!doctype html>\n<!-- Generated by tools/build_explorer_gateway.py; edit the explorer source. -->",
        1,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(SOURCE.read_text(encoding="utf-8"))
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != expected:
            raise RuntimeError("Root explorer differs from its canonical source")
        print("Root explorer matches its source and rebased links.")
    else:
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
        print("Wrote docs/index.html from the explorer source.")


if __name__ == "__main__":
    main()
